version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "online-fold"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yvhha51lpg7r"
s3_prefix = "online-fold"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
